import test from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { readFileSync,readdirSync,mkdtempSync,rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { handleApi } from "../../Home Page/server/api.mjs";
import { catalogSchema,selectProducts } from "../shared/catalog.mjs";
const product={id:"test-expert",title:"QA strategy",titleFa:"استراتژی آزمایشی",description:"Test description",descriptionFa:"توضیح آزمایشی",creator:"QA",image:"/assets/brand.webp",platforms:["mt5"],strategyType:"swing",price:99,badge:"none",access:"public",verifiedResults:true,profitFactor:2.1,winRate:68,maxDrawdown:12,currency:"USD",status:"published",createdAt:"2026-09-29T00:00:00.000Z",updatedAt:"2026-09-29T00:00:00.000Z"};
function adapter(sqlite){return{prepare(sql){const stmt=sqlite.prepare(sql);return{bind(...v){return{async first(){return stmt.get(...v)||null},async run(){return stmt.run(...v)}}}}}}}
function setup(file=":memory:"){const sqlite=new DatabaseSync(file);for(const f of readdirSync("drizzle").filter(f=>f.endsWith(".sql")))sqlite.exec(readFileSync("drizzle/"+f,"utf8"));return{sqlite,db:adapter(sqlite)}}
const get=(path="/api/experts")=>new Request("https://example.test"+path);
const put=(products,revision=0,origin="https://example.test")=>new Request("https://example.test/api/admin/experts",{method:"PUT",headers:{"content-type":"application/json",origin},body:JSON.stringify({config:{products},revision})});
test("expert catalog is isolated, owner-only and drafts stay private",async()=>{const {db,sqlite}=setup();const home=await (await handleApi(get("/api/home"),db,null)).json();assert.deepEqual((await (await handleApi(get(),db,null)).json()).config.products,[]);assert.equal((await handleApi(put([product]),db,null)).status,401);assert.equal((await handleApi(get("/api/admin/experts"),db,"owner")).status,200);assert.equal((await handleApi(put([product]),db,"other")).status,403);assert.equal((await handleApi(put([product],0,"https://evil.test"),db,"owner")).status,403);const draft={...product,id:"draft",status:"draft",image:"",description:"",verifiedResults:false,profitFactor:null,winRate:null,maxDrawdown:null};assert.equal((await handleApi(put([product,draft]),db,"owner")).status,200);assert.equal((await handleApi(put([]),db,"owner")).status,409);assert.deepEqual((await (await handleApi(get(),db,null)).json()).config.products.map(p=>p.id),["test-expert"]);assert.equal((await (await handleApi(get("/api/admin/experts"),db,"owner")).json()).config.products.length,2);assert.deepEqual(await (await handleApi(get("/api/home"),db,null)).json(),home);sqlite.close()});
test("expert catalog survives database reopen",async()=>{const dir=mkdtempSync(join(tmpdir(),"gor-experts-")),file=join(dir,"db.sqlite");let {sqlite,db}=setup(file);await handleApi(put([product]),db,"owner");sqlite.close();sqlite=new DatabaseSync(file);db=adapter(sqlite);assert.equal((await (await handleApi(get(),db,null)).json()).config.products[0].title,"QA strategy");sqlite.close();rmSync(dir,{recursive:true})});
test("expert schema rejects incomplete products and incomplete verified metrics",()=>{for(const patch of [{image:""},{description:""},{image:"https://evil.test/a.png"},{price:-1},{platforms:[]},{verifiedResults:true,profitFactor:null}])assert.equal(catalogSchema.safeParse({products:[{...product,...patch}]}).success,false);assert.equal(catalogSchema.safeParse({products:[product,product]}).success,false)});
test("expert filters combine platform/type/price/verified",()=>{const products=[product,{...product,id:"two",title:"Scalper",price:20,platforms:["ctrader"],strategyType:"scalping",verifiedResults:false,profitFactor:null,winRate:null,maxDrawdown:null},{...product,id:"hidden",status:"draft"}];assert.equal(selectProducts(products,{query:"استراتژی"}).length,2);assert.deepEqual(selectProducts(products,{platform:["mt5"],strategyType:["swing"],maxPrice:100,verifiedOnly:true}).map(p=>p.id),["test-expert"]);assert.equal(selectProducts(products,{platform:["ctrader"],verifiedOnly:true}).length,0);assert.deepEqual(selectProducts(products,{sort:"price-low"}).map(p=>p.price),[20,99])});
